### ISSUE TITLE
I am getting UnsatisfiedLinkError exception

### ISSUE THREAD

**Issue by chenjing1294** [ikvm-revived/ikvm#114]
Unhandled exception:  org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient ---> java.lang.UnsatisfiedLinkError: sun/nio/ch/ServerSocketChannelImpl.initIDs()V
   at IKVM.Runtime.JNI.Frame.GetFuncPtr(CallerID callerID, String clazz, String name, String sig)
   at sun.nio.ch.ServerSocketChannelImpl.initIDs()
   at sun.nio.ch.ServerSocketChannelImpl..cctor()
   --- End of inner exception stack trace ---
   at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(AdminClientConfig , TimeoutProcessorFactory , HostResolver )
   at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(AdminClientConfig , TimeoutProcessorFactory )
   at org.apache.kafka.clients.admin.Admin.create(Properties props)
   at org.apache.kafka.clients.admin.AdminClient.create(Properties props)
   at com.redisant.admin.AdminClient..ctor()
   at CallJava.Program.Main(String[] args)

> ikvm 8.2.0：
> ikvmc -target:library zstd-jni-1.5.0-4.jar
> ikvmc -target:library snappy-java-1.1.8.4.jar 
> ikvmc -target:library slf4j-api-1.7.30.jar
> ikvmc -target:library lz4-java-1.8.0.jar
> 
> ikvmc -target:library kafka-clients-3.1.0.jar -r:zstd-jni-1.5.0-4.dll -r:snappy-java-1.1.8.4.dll -r:slf4j-api-1.7.30.dll -r:lz4-java-1.8.0.dll

**Comment by wasabii** [comment]
Can you try with 8.2.1? I believe this bug was fixed in 8.2.1.

**Comment by wasabii** [comment]
I should also say that unless you have a special need to run ikvmc by hand, using IKVM.Maven.Sdk or IkvmReferences are vastly preferable.

**Comment by chenjing1294** [comment]
> Can you try with 8.2.1? I believe this bug was fixed in 8.2.1.

I tried it just now and version 8.2.1 fixed it, you guys are awesome.
