### ISSUE TITLE
java.beans.Introspector.findExplicitBeanInfo(Class beanClass) may throw unhandled ClassNotFoundException in .cctor

### ISSUE THREAD

**Issue by oising** [ikvm-revived/ikvm#137]
This popped up this morning in org.apache.log4j.LoggerManager's c# static cctor as:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'org.semanticweb.elk.cli.Main' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'org.apache.log4j.LogManager' threw an exception.
 ---> ClassNotFoundException: org.apache.log4j.PatternLayoutBeanInfo
   at IKVM.Java.Externs.java.lang.Class.forName0(String name, Boolean initialize, ClassLoader loader, Class caller)
   at java.lang.Class.forName0(String name, Boolean initialize, ClassLoader loader, Class caller)
   at java.lang.Class.forName(String name, Boolean initialize, ClassLoader loader, CallerID )
   at com.sun.beans.finder.ClassFinder.findClass(String name, ClassLoader loader)
   at com.sun.beans.finder.InstanceFinder.instantiate(Class type, String name)
   at com.sun.beans.finder.InstanceFinder.find(Class type)
   at java.beans.Introspector.findExplicitBeanInfo(Class beanClass)
   at java.beans.Introspector..ctor(Class beanClass, Class stopClass, Int32 flags)
   at java.beans.Introspector.getBeanInfo(Class beanClass)
   at org.apache.log4j.config.PropertySetter.introspect()
   at org.apache.log4j.config.PropertySetter.getPropertyDescriptor(String name)
   at org.apache.log4j.config.PropertySetter.setProperty(String name, String value)
   at org.apache.log4j.config.PropertySetter.setProperties(Properties properties, String prefix)
   at org.apache.log4j.config.PropertySetter.setProperties(Object obj, Properties properties, String prefix)
   at org.apache.log4j.PropertyConfigurator.parseAppender(Properties props, String appenderName)
   at org.apache.log4j.PropertyConfigurator.parseCategory(Properties props, Logger logger, String optionKey, String loggerName, String value)
   at org.apache.log4j.PropertyConfigurator.configureRootCategory(Properties props, LoggerRepository hierarchy)
   at org.apache.log4j.PropertyConfigurator.doConfigure(Properties properties, LoggerRepository hierarchy)
   at org.apache.log4j.PropertyConfigurator.doConfigure(URL configURL, LoggerRepository hierarchy)
   at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(URL url, String clazz, LoggerRepository hierarchy)
   at org.apache.log4j.LogManager..cctor()
   --- End of inner exception stack trace ---
   at org.apache.log4j.LogManager.getLogger(String name)
   at org.apache.log4j.Logger.getLogger(Class clazz)
   at org.semanticweb.elk.cli.Main..cctor()
   --- End of inner exception stack trace ---
   at org.semanticweb.elk.cli.Main.main(String[] args)
   ```

I am no java expert, but about 19 years ago, one was asked the same question I've been asking myself all day, and he had this to say:

> Part of the JavaBean model says that for the given Java class, there _might_
> be a corresponding *BeanInfo class. The java.bean.Introspector, which is
> normally the place to get a BeanInfo from will either try to find a matching
> class, and if not found, will use reflection itself. The error therefore is
> expected by the Introspector and silently caught and moves on to using
> reflection to find the BeanInfo. You have just exposed something via
> low-level logging getting a BeanInfo and the JavaBean framework is doing
> it's best to find things.
> 
> See the java.bean package and in particular the Introspector class for more
> information.

see: https://log4j-user.logging.apache.narkive.com/BlwOezvY/anyone-knows-about-org-apache-log4j-layoutbeaninfo#post3

This is a log4j 1.2.x, used by the maven package: https://mvnrepository.com/artifact/org.semanticweb.elk/elk-cli

It seems that in the IKVM context, this exception is not swallowed and is instead bubbled up. To repro, here's my csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="IKVM" Version="8.2.1" />
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.1" />
        <MavenReference Include="org.semanticweb.elk:elk-cli" Version="0.4.3" />
    </ItemGroup>
</Project>
```
and here's `Program.cs` -- comment out the systemProperty code to trigger the bug. I decompiled the dotnet log4j.dll to figure out a workaround, and saw that this prop would force an early return.

```csharp
// See https://aka.ms/new-console-template for more information
Console.WriteLine("elk-cli dotnet wrapper (ikvm)");

// evade TypeInitializationException
java.lang.System.setProperty("log4j.defaultInitOverride", "true");

org.semanticweb.elk.cli.Main.main(args);
```
Using dotnet 6.0.400

Thanks for a great release -- everything else seems flawless (so far)

**Comment by wasabii** [comment]
Think I found this guy while working on something else. The AppDomainAssemblyClassLoader extern was throwing a ClassNotFoundException. Except, it was throwing the wrong one. It was throwing ClassNotFoundException, when it should have been throwing a java.lang.ClassNotFoundException. The first being a retargetable .NET exception (used for exceptions that should automatically be converted to a special Java-version when entering Java code, but retain their .NET identity otherwise).

Fix is currently on my JavaTest branch. But i'll probably get it in separately.
