### ISSUE TITLE
Compiler error on netstandard in Prerelease 8.2.2

### ISSUE THREAD

**Issue by digiholic** [ikvm-revived/ikvm#148]
While attempting to use `IKVM-8.2.2-prerelease.241-tools-ikvmc-netcoreapp3.1` from the releases page, I get this error attempting to create a library of a jar file:

```
ikvmc (8.2.2-prerelease.241+Branch.develop.Sha.9337ee343a42e65cc890da8c5b3b0ea312c992a3)
Copyright c 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug


*** INTERNAL COMPILER ERROR ***

PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE

ikvmc, Version=8.2.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
C:\Users\mfournier\IKVM-8.2.2-prerelease.241-tools-ikvmc-netcoreapp3.1\win7-x64\
3.1.28 64-bit

System.IO.FileNotFoundException: netstandard
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in D:\a\ikvm\ikvm\src\IKVM.Reflection\Universe.cs:line 788
   at IKVM.Internal.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList`1 references, IList`1 userLibPaths) in D:\a\ikvm\ikvm\src\ikvmc\IKVM\Internal\AssemblyResolver.cs:line 93
   at ikvmc.IkvmcCompiler.Compile(String[] args) in D:\a\ikvm\ikvm\src\ikvmc\IkvmcCompiler.cs:line 178
   at ikvmc.IkvmcCompiler.Main(String[] args) in D:\a\ikvm\ikvm\src\ikvmc\IkvmcCompiler.cs:line 112
   ```
   
   
The command I am using is `ikvmc.exe -target:library myJar.jar`. I can confirm that the `netstandard.dll` is included in the `win7-x64` folder.

**Comment by wasabii** [comment]
Duplicate #142
