### ISSUE TITLE
The newest minecraft launcher+minecraft server jar's give errors.

### ISSUE THREAD

**Issue by kevincrans** [ikvm-revived/ikvm#175]
This is Windows 11 x64 using 8.2.1-tools-ikvm-netcoreapp on .net 6.0.3.

The newest minecraft launcher jar is outdated.
However, launching minecraft 1.0 from a launcher that is not outdated opens a terminal and closes 2 times, with or without -jar and with, the launcher doesn't re-open but stays inactive and needs to be closed from task manager (the newest version just says jvm's incompatible and needs the built in).

The old jar and server actually give output when run from the cmd, although the first line is about the unsupported awt, so u might skip to the server.jar.
<details>
<summary>cmd output</summary>

```C:\Program Files\IKVM-bin-netcoreapp>ikvm -jar C:\Users\Administrator\Downloads\minecraft.jar
Exception in thread "main" java.lang.Error: Could not find class: ikvm.awt.NetGraphicsEnvironment, @AWTASSEMBLY@
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Reflection.Emit.MethodBuilder.GetParameters()
   at IKVM.Internal.DynamicTypeWrapper.GetMethodBaseToken(MethodBase mb) in D:\a\ikvm\ikvm\src\IKVM.Runtime\DynamicTypeWrapper.cs:line 6913
   at IKVM.Internal.DynamicTypeWrapper.GetSourceLineNumber(MethodBase mb, Int32 ilOffset) in D:\a\ikvm\ikvm\src\IKVM.Runtime\DynamicTypeWrapper.cs:line 6928
   at IKVM.Internal.ExceptionHelper.GetLineNumber(StackFrame frame) in D:\a\ikvm\ikvm\src\IKVM.Runtime\ExceptionHelper.cs:line 371
   at IKVM.Internal.ExceptionHelper.ExceptionInfoHelper.Append(List`1 stackTrace, StackTrace st, Int32 skip, Boolean isLast) in D:\a\ikvm\ikvm\src\IKVM.Runtime\ExceptionHelper.cs:line 219
   at IKVM.Internal.ExceptionHelper.ExceptionInfoHelper.get_StackTrace(Exception t) in D:\a\ikvm\ikvm\src\IKVM.Runtime\ExceptionHelper.cs:line 126
   at IKVM.Internal.ExceptionHelper.getOurStackTrace(Exception x) in D:\a\ikvm\ikvm\src\IKVM.Runtime\ExceptionHelper.cs:line 695
   at java.lang.ThrowableHelper.getOurStackTrace(Exception _this)
   at java.lang.ThrowableHelper.printStackTrace(Exception _this, PrintStreamOrWriter s)
   at java.lang.ThrowableHelper.printStackTrace(Exception _this, PrintStream s)
   at java.lang.Throwable.printStackTrace(PrintStream s)
   at java.lang.Throwable.instancehelper_printStackTrace(Exception this, PrintStream s)
   at java.lang.ThreadGroup.uncaughtException(Thread t, Exception e)
   at java.lang.ThreadGroup.uncaughtException(Thread t, Exception e)
   at Starter.Main(String[] args) in D:\a\ikvm\ikvm\src\ikvm\starter.cs:line 339

C:\Program Files\IKVM-bin-netcoreapp>ikvm -jar C:\Users\Administrator\Downloads\server.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: net.minecraft.bundler.Main (61.0)
        at IKVM.Java.Externs.java.lang.ClassLoader.defineClass1(ClassLoader.cs:63)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:772)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(AccessController.java:310)
        at java.security.AccessController.doPrivileged(AccessController.java:718)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:440)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:375)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
</details>

Is this useful information for the improvement of ikvm, or do you recommend me to try other things?
[latest.log](https://github.com/ikvm-revived/ikvm/files/9678187/latest.log)

**Comment by wasabii** [comment]
IKVM at this point does not support AWT.

The second error is about an unsupported class file version. IKVM only implements and supports JDK8. A JAR file containing classes compiled for JDK9 and above will not work.

**Comment by wasabii** [comment]
#144 #120

**Comment by wasabii** [comment]
Worth trying this again now that we have AWT support.
