### ISSUE TITLE
Build Error: Incorrect IKVM.MSBuild path when swapping IKVM PackageReference versions

### ISSUE THREAD

**Issue by NightOwl888** [ikvm-revived/ikvm#181]
I have seen this several times in 8.2.2-prerelease0553 and now again in 8.2.2-pullrequest0180-0292. When changing a PackageReference from one version to another of IKVM (in this case, I started with 8.2.2-prerelease0553 and changed to 8.2.2-pullrequest0180-0292), it is looking for a directory that doesn't exist.

### Build Log

```console
Build started...
Restored F:\Projects\_Demos\IKVM_JUnit_VintageTestEngine_Issue\IKVM_JUnit_VintageTestEngine_Issue\IKVM_JUnit_VintageTestEngine_Issue.csproj (in 17 ms).
1>------ Build started: Project: IKVM_JUnit_VintageTestEngine_Issue, Configuration: Debug Any CPU ------
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018: The "IkvmGetReferenceAssemblies" task failed unexpectedly.
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\bin\ikvmc\net461\any\refs'.
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at System.IO.Directory.GetFiles(String path, String searchPattern)
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmGetReferenceAssemblies.<GetReferenceAssemblies>d__13.MoveNext()
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmGetReferenceAssemblies.Execute() in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmGetReferenceAssemblies.cs:line 45
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\buildTransitive\netstandard2.0\IKVM.MSBuild.Tasks.targets(22,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "IKVM_JUnit_VintageTestEngine_Issue.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### .csproj File

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <DebugMavenReferences>false</DebugMavenReferences>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.1" />
    <PackageReference Include="IKVM" Version="8.2.2-pullrequest0180-0292" />
  </ItemGroup>

  <ItemGroup>
    <MavenReference Include="org.junit.jupiter:junit-jupiter" Version="5.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.jupiter:junit-jupiter-api" Version="5.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.jupiter:junit-jupiter-engine" Version="5.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.jupiter:junit-jupiter-migrationsupport" Version="5.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.jupiter:junit-jupiter-params" Version="5.9.1" Debug="$(DebugMavenReferences)" />
    
    <MavenReference Include="org.junit.platform:junit-platform-commons" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-console" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-engine" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-jfr" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-launcher" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-reporting" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-runner" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-suite" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-suite-api" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-suite-commons" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-suite-engine" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    <MavenReference Include="org.junit.platform:junit-platform-testkit" Version="1.9.1" Debug="$(DebugMavenReferences)" />
    
    <MavenReference Include="org.junit.vintage:junit-vintage-engine" Version="5.9.1" Debug="$(DebugMavenReferences)" />
  </ItemGroup>

</Project>
```

Cleaning doesn't help. Rebuilding doesn't help. Even reloading the solution doesn't help. The only way to get by the error is to completely close Visual Studio and restart it. Kind of annoying. Since changing a NuGet package version is a thing that happens during regular development, we should fix this before the next public prerelease.

```
// Looking for
F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\bin\ikvmc\net461\any\refs

// It is actually at
F:\Users\shad\.nuget\packages\ikvm.msbuild\8.2.2-pullrequest0180-0292\bin\ikvmc\net461\win7-x64\refs
```

**Comment by wasabii** [comment]
As far as I know, there is no way around this. Or none I have been able to find. The problem is without restarting VS, it will never unload the custom Tasks. It will just keep using the old ones.

**Comment by wasabii** [comment]
Give this a try with latest develop.

**Comment by wasabii** [comment]
Stale.....
