### ISSUE TITLE
Build error: The method or operation is not implemented.

### ISSUE THREAD

**Issue by chenjing1294** [ikvm-revived/ikvm#205]
Does IKVM 8.2.3 support Apple M1 chip? When I compile the project I get the following error:
```
  IKVM.targets(17, 9): [MSB4018] "IkvmGetReferenceAssemblies".
System.NotImplementedException: The method or operation is not implemented.
   at IKVM.Tool.Compiler.IkvmCompilerLauncher.GetToolDir(IkvmCompilerTargetFramework framework, OSPlatform platform, Architecture architecture) in D:\a\ikvm\ikvm\src\IKVM.Tool\Compiler\IkvmCompilerLauncher.cs:line 107
   at IKVM.Tool.Compiler.IkvmCompilerLauncher.GetReferenceAssemblyDirectory(IkvmCompilerTargetFramework framework, OSPlatform platform, Architecture architecture) in D:\a\ikvm\ikvm\src\IKVM.Tool\Compiler\IkvmCompilerLauncher.cs:line 151
   at IKVM.Tool.Compiler.IkvmCompilerLauncher.GetReferenceAssemblyDirectory(IkvmCompilerTargetFramework framework) in D:\a\ikvm\ikvm\src\IKVM.Tool\Compiler\IkvmCompilerLauncher.cs:line 163
   at IKVM.MSBuild.Tasks.IkvmGetReferenceAssemblies.GetReferenceAssemblies()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at IKVM.MSBuild.Tasks.IkvmGetReferenceAssemblies.Execute() in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmGetReferenceAssemblies.cs:line 44
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

**Comment by wasabii** [comment]
No. Not yet.

**Comment by chenjing1294** [comment]
thanks. Looking forward to the follow-up version to support the Apple M1 chip

**Comment by wasabii** [comment]
Help is always appreciated.
