### ISSUE TITLE
8.3.3 net461: ikvmstub throws exception when trying to display help text

### ISSUE THREAD

**Issue by joniles** [ikvm-revived/ikvm#243]
Trivial issue: when `ikvmstub` is invoked without arguments, the help text generation throws an exception as shown below. `ikvmc.exe` displays the expected text without error. This issue does not occur with the netcoreapp3.1 version. .NET Framework 4.8 is installed.

```
C:\Users\Jon\Downloads\IKVM-8.3.3-tools-net461-win7-x64> .\ikvmstub.exe
Option '--out' is required.
Required argument missing for command: 'ikvmstub'.

Description:

Usage:
  ikvmstub <assemblyNameOrPath> [options]

Arguments:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at System.CommandLine.Help.HelpBuilder.WriteColumns(IReadOnlyList`1 items, HelpContext context)
   at System.CommandLine.Help.HelpBuilder.Write(HelpContext context)
   at System.CommandLine.Invocation.ParseErrorResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.GetExitCode(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<<InvokeAsync>g__FullInvocationChainAsync|2_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.CommandExtensions.<InvokeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ikvmstub.Program.<Main>(String[] args)
C:\Users\Jon\Downloads\IKVM-8.3.3-tools-net461-win7-x64>
```

**Comment by wasabii** [comment]
This should be resolved in 8.4.0.
