### ISSUE TITLE
NewWeakGlobalRef allocates GCHandle to boxed reference, not unwrapped object

### ISSUE THREAD

**Issue by joniles** [ikvm-revived/ikvm#248]
Background: testing the "revived" version of IKVM with a view to migrating [MPXJ](https://github.com/joniles/mpxj) off of the "classic" version of IKVM.

My MPXJ test suite runs successfully for `net451` and `netcoreapp3.1` using the classic version of IKVM. With the new version of IKVM I'm hitting problems with SQLite and JNI. The recently released changes in https://github.com/ikvm-revived/ikvm/pull/240 moved me further forward, but we're still not quite there.

I have attached a self-contained test case, which uses IKVM.Maven.Sdk 1.2.0, and updates IKVM to 8.4.2.

When using `net461` this is the stack trace I get:

```
C:\users\jon\source\repos\ikvm-sqlite-jni\ikvm-sqlite-jni\bin\Debug\net461> .\ikvm-sqlite-jni.exe
*** exception in native code ***
System.InvalidOperationException: Handle is not initialized.
   at System.Runtime.InteropServices.GCHandle.FromIntPtr(IntPtr value)
   at IKVM.Internal.MemberWrapper.FromCookieImpl(IntPtr cookie)
   at IKVM.Runtime.JNI.JNIEnv.GetFieldAccessor(IntPtr cookie)
   at IKVM.Runtime.JNI.JNIEnv.GetLongField(JNIEnv* pEnv, IntPtr obj, IntPtr fieldID)
   at org.sqlite.core.NativeDB._open_utf8(Byte[] barr, Int32 i)

Unhandled Exception: net.sf.mpxj.MPXJException: Invalid file format ---> net.sf.mpxj.MPXJException: Invalid file format
---> java.lang.ClassCastException: Unable to cast object of type 'System.IntPtr' to type 'java.lang.Class'.
   at IKVM.Runtime.JNI.JNIFrame.Leave()
   at org.sqlite.core.NativeDB._open_utf8(Byte[] barr, Int32 i)
   at org.sqlite.core.NativeDB._open(String file, Int32 openFlags) in NativeDB.java:line 81
   at org.sqlite.core.DB.open(String file, Int32 openFlags) in DB.java:line 195
   at org.sqlite.SQLiteConnection.open(String url, String origFileName, Properties props) in SQLiteConnection.java:line 248
   at org.sqlite.SQLiteConnection..ctor(String url, String fileName, Properties prop) in SQLiteConnection.java:line 61
   at org.sqlite.jdbc3.JDBC3Connection..ctor(String url, String fileName, Properties prop) in JDBC3Connection.java:line 28
   at org.sqlite.jdbc4.JDBC4Connection..ctor(String url, String fileName, Properties prop) in JDBC4Connection.java:line 21
   at org.sqlite.JDBC.createConnection(String url, Properties prop) in JDBC.java:line 115
   at net.sf.mpxj.common.SQLite.createConnection(File file, Properties props) in SQLite.java:line 78
   at net.sf.mpxj.common.SQLite.createConnection(File file) in SQLite.java:line 58
   at net.sf.mpxj.reader.UniversalProjectReader.populateSqliteTableNames(File file) in UniversalProjectReader.java:line 874
   at net.sf.mpxj.reader.UniversalProjectReader.handleSQLiteFile(InputStream stream) in UniversalProjectReader.java:line 548
   at net.sf.mpxj.reader.UniversalProjectReader.readInternal(File file, InputStream inputStream) in UniversalProjectReader.java:line 292
   --- End of inner exception stack trace ---
   at net.sf.mpxj.reader.UniversalProjectReader.readInternal(File file, InputStream inputStream) in UniversalProjectReader.java:line 370
   at net.sf.mpxj.reader.UniversalProjectReader.handleFile(File file) in UniversalProjectReader.java:line 610
   at net.sf.mpxj.reader.UniversalProjectReader.readInternal(File file) in UniversalProjectReader.java:line 158
   --- End of inner exception stack trace ---
   at net.sf.mpxj.reader.UniversalProjectReader.readInternal(File file) in UniversalProjectReader.java:line 164
   at net.sf.mpxj.reader.UniversalProjectReader.readAll(File file) in UniversalProjectReader.java:line 144
   at net.sf.mpxj.reader.UniversalProjectReader.readAll(String fileName) in UniversalProjectReader.java:line 131
   at ikvm_sqlite_jni.Program.Main(String[] args)
C:\users\jon\source\repos\ikvm-sqlite-jni\ikvm-sqlite-jni\bin\Debug\net461>
```

When using `netcoreapp3.1` this is the stack trace I get:

```
C:\users\jon\source\repos\ikvm-sqlite-jni\ikvm-sqlite-jni\bin\Debug\netcoreapp3.1> .\ikvm-sqlite-jni.exe
*** exception in native code ***
System.InvalidOperationException: Handle is not initialized.
   at System.Runtime.InteropServices.GCHandle.FromIntPtr(IntPtr value)
   at IKVM.Internal.MemberWrapper.FromCookieImpl(IntPtr cookie)
   at IKVM.Internal.FieldWrapper.FromCookie(IntPtr cookie)
   at IKVM.Runtime.JNI.JNIEnv.GetFieldAccessor(IntPtr cookie)
   at IKVM.Runtime.JNI.JNIEnv.GetLongField(JNIEnv* pEnv, IntPtr obj, IntPtr fieldID)
   at org.sqlite.core.NativeDB._open_utf8(Byte[] barr, Int32 i)
Unhandled exception. net.sf.mpxj.MPXJException: Invalid file format
C:\users\jon\source\repos\ikvm-sqlite-jni\ikvm-sqlite-jni\bin\Debug\netcoreapp3.1>
```
Test project:
[ikvm-sqlite-jni.zip](https://github.com/ikvm-revived/ikvm/files/10324729/ikvm-sqlite-jni.zip)
You should just be able to build and run the resulting executable to reproduce the problem.

**Comment by wasabii** [comment]
So the issue here is related to an error introduced when moving the allocation code for NewWeakLocalRef into the JNIGlobalRefTable. Instead of allocating a global ref from the unwrapped object, the code allocates a reference to the nint reference itself. And since .NET allows that (boxing) it compiled without error.

Test cases are being added to hotfix/8.4.3 to cover NewWeakGlobalRef.

**Comment by joniles** [comment]
Thank you! Tested and working as expected here.
