### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by toddmcintosh** [ikvm-revived/ikvm#292]
I'm trying to use IkvnmReference to compile a copy of Apache's FOP (fop.jar) using Ikvm 8.4.5. I've been getting multiple ****The "IkvmReferenceItemPrepare"** task failed unexpectedly** errors. 

The latest one has to do with the application trying to acces the "Documents and Settings" folder to which access is denied in Windows 10. I've run Visual Studio in admin mode, and this still did not help.

Here's the error in the build output. Any advice would be appreciated.

```
Build started...
1>------ Build started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018: The "IkvmReferenceItemPrepare" task failed unexpectedly.
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018: System.UnauthorizedAccessException: Access to the path 'C:\Documents and Settings' is denied.
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1.MoveNext()
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmReferenceItemPrepare.<ExpandPath>d__40.MoveNext() in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmReferenceItemPrepare.cs:line 309
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmReferenceItemPrepare.ExpandCompile(IkvmReferenceItem item) in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmReferenceItemPrepare.cs:line 269
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmReferenceItemPrepare.AssignMetadata(IkvmReferenceItem item) in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmReferenceItemPrepare.cs:line 195
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmReferenceItemPrepare.AssignMetadata(IEnumerable`1 items) in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmReferenceItemPrepare.cs:line 179
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmReferenceItemPrepare.Execute() in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmReferenceItemPrepare.cs:line 161
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.targets(37,9): error MSB4018:    at Microsoft.Build.CommandLine.OutOfProcTaskAppDomainWrapperBase.InstantiateAndExecuteTask(IBuildEngine oopTaskHostNode, LoadedType taskType, String taskName, String taskLocation, String taskFile, Int32 taskLine, Int32 taskColumn, AppDomainSetup appDomainSetup, IDictionary`2 taskParams)
1>Done building project "ClassLibrary1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by toddmcintosh** [comment]
As a followup I've tried a few different versions of the build (8.4, 8.2) and I'm getting the same error. I'm assuming this means  it's an issue with my machine? If you could point me in the right direction I would appreciate it.

**Comment by wasabii** [comment]
Would help to see the IkvmReference line you're using. This is a very odd error.

**Comment by wasabii** [comment]
Also, just so you know, given that FOP is a well published and maintained library, you can probably just access it through Maven.

[http](https://www.nuget.org/packages/IKVM.Maven.Sdk)

**Comment by toddmcintosh** [comment]
I thought I was having issues with a networked drive so I ended up just putting it in the root of C.

```
	<ItemGroup>
		<IkvmReference Include="C:\fop.jar">
			<AssemblyName>Fop23</AssemblyName>
			<AssemblyVersion>2.3</AssemblyVersion>
			<AssemblyFileVersion>2.3</AssemblyFileVersion>
		</IkvmReference>
	</ItemGroup>
```

**Comment by toddmcintosh** [comment]
When I try to add IKVM.Maven.Sdk to an empty .NET Standard 2.0 class library, I get this build error:

```
Build started...
1>------ Build started: Project: ClassLibrary3, Configuration: Debug Any CPU ------
1>C:\Users\toddmcintosh1\.nuget\packages\ikvm.msbuild\8.4.4\buildTransitive\netstandard2.0\IKVM.MSBuild.targets(39,9): error : Could not locate IKVM.Runtime.dll.
1>Done building project "ClassLibrary3.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by toddmcintosh** [comment]
Is there something being cached from before that is blocking the maven package from running?

**Comment by wasabii** [comment]
Oh. We don't support .NET standard at all. So that's one issue. Not even IkvmReference supports it.

**Comment by wasabii** [comment]
Can you try just putting the time someplace other than C?

**Comment by toddmcintosh** [comment]
So I was able to get the IKVM.Maven.Sdk package to load in my project, and the maven repo indeed has a Fop artifact, and I as able to use this strategy to load Fop into my .NET Core 6 project. Thank you so much for the direction, I had no experience with the world of Maven before! Cheers.

**Comment by wasabii** [comment]
Neato. Let's leave this issue open, as it does represent something that's broken. Some error with IkvmReference when using the C:\ drive directly.
