### ISSUE TITLE
Running junit.dll fails for .NET core

### ISSUE THREAD

**Issue by igorkwwrd** [ikvm-revived/ikvm#30]
I'm building junit.dll like this

```
ikvmc.exe ^
-platform:anycpu ^
-target:library ^
-out:junit.dll ^
-r:System.Runtime.Extensions.dll ^
-r:System.Runtime.dll ^
-r:System.Threading.dll ^
-r:System.Threading.Thread.dll ^
junit.jar ^
hamcrest-core.jar
```

then calling ```org.junit.runner.JUnitCore.main(args)``` from a console
program.

Under .NET framework there is no issues.  It runs OK.

```
JUnit version 4.13
Time: 0.004
OK (0 tests)
```

Under .NET core it fails.

```
JUnit version 4.13
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at __<Invoker>(Object[] )
   at Java_sun_reflect_ReflectionFactory.FastConstructorAccessorImpl.newInstance(Object[] args) in C:\Users\igor\ikvm-revived\runtime\IKVM.Runtime\openjdk\sun.reflect.cs:line 920
   at java.lang.reflect.Constructor.newInstance(Object[] initargs, CallerID )
   at java.lang.reflect.Proxy.newProxyInstance(ClassLoader loader, Class[] interfaces, InvocationHandler h, CallerID )
   at sun.reflect.annotation.AnnotationParser.1.run()
   at sun.reflect.annotation.AnnotationParser.1.run()
   at java.security.AccessController.doPrivileged(Object action, AccessControlContext context, CallerID callerID)
   at java.security.AccessController.doPrivileged(PrivilegedAction action, CallerID )
   at sun.reflect.annotation.AnnotationParser.annotationForMap(Class type, Map memberValues)
   at Java_java_lang_Class.FreezeOrWrapAttribute(Annotation ann) in C:\Users\igor\ikvm-revived\runtime\IKVM.Runtime\openjdk\java.lang.cs:line 459
   at Java_java_lang_Class.AnnotationsToMap(ClassLoaderWrapper loader, Object[] objAnn) in C:\Users\igor\ikvm-revived\runtime\IKVM.Runtime\openjdk\java.lang.cs:line 432
   at Java_java_lang_Class.getDeclaredAnnotationsImpl(Class thisClass) in C:\Users\igor\ikvm-revived\runtime\IKVM.Runtime\openjdk\java.lang.cs:line 480
   at java.lang.Class.getDeclaredAnnotationsImpl()
   at java.lang.Class.createAnnotationData(Int32 classRedefinedCount)
   at java.lang.Class.annotationData()
   at java.lang.Class.getAnnotation(Class annotationClass)
   at java.lang.reflect.AnnotatedElement.<default>isAnnotationPresent(AnnotatedElement , Class )
   at java.lang.Class.isAnnotationPresent(Class annotationClass)
   at org.junit.runner.notification.RunNotifier.wrapIfNotThreadSafe(RunListener )
   at org.junit.runner.notification.RunNotifier.addFirstListener(RunListener listener)
   at org.junit.runner.JUnitCore.run(Runner runner)
   at org.junit.runner.JUnitCore.run(Request request)
   at org.junit.runner.JUnitCore.runMain(JUnitSystem , String[] )
   at org.junit.runner.JUnitCore.main(String[] args)
   at TestRunner.Program.Main(String[] args) in C:\Users\igor\Jenova\engine\DotNetEngine\WindwardReports\TestRunner\Program.cs:line 9
```

It happens inside IKVM.Runtime.dll, file sun.reflect.cs,
class FastConstructorAccessorImpl, method ```newInstance``` where it calls
```invoker(args)```.

I suppose the code being executed is created in the FastConstructorAccessorImpl
constructor.  The code is creating dynamically.

Currently I'm trying to study the problem.  If someone has any comments,
suggestions, etc. you are welcome.

**Comment by TylerDurden23** [comment]
I am seeing the same issue: 

 at Java_sun_reflect_ReflectionFactory.FastConstructorAccessorImpl.newInstance(Object[] args)
   at java.lang.reflect.Constructor.newInstance(Object[] initargs, CallerID )
   at java.lang.reflect.Proxy.newProxyInstance(ClassLoader loader, Class[] interfaces, InvocationHandler h, CallerID )
   at sun.reflect.annotation.AnnotationParser.1.run()
   at sun.reflect.annotation.AnnotationParser.1.run()
   at java.security.AccessController.doPrivileged(Object action, AccessControlContext context, CallerID callerID)
   at java.security.AccessController.doPrivileged(PrivilegedAction action, CallerID )
   at sun.reflect.annotation.AnnotationParser.annotationForMap(Class type, Map memberValues)
   at Java_java_lang_Class.FreezeOrWrapAttribute(Annotation ann)
   at Java_java_lang_Class.AnnotationsToMap(ClassLoaderWrapper loader, Object[] objAnn)
   at Java_java_lang_reflect_Field.getDeclaredAnnotationsImpl(Field thisField)
   at java.lang.reflect.Field.getDeclaredAnnotationsImpl()
   at java.lang.reflect.Field.declaredAnnotations()
   at java.lang.reflect.Field.declaredAnnotations()
   at java.lang.reflect.Field.getDeclaredAnnotations()
   at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector._findFields(TypeResolutionContext , JavaType , Map )
   at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector._findFields(TypeResolutionContext , JavaType , Map )
   at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector.collect(TypeResolutionContext , JavaType )
   at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector.collectFields(AnnotationIntrospector intr, TypeResolutionContext tc, MixInResolver mixins, TypeFactory types, JavaType type)
   at com.fasterxml.jackson.databind.introspect.AnnotatedClass._fields()
   at com.fasterxml.jackson.databind.introspect.AnnotatedClass.fields()
   at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(Map props)
   at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll()
   at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor()
   at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor()
   at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(SerializerProvider prov, JavaType type, BeanDescription beanDesc)
   at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildMapSerializer(SerializerProvider prov, MapType type, BeanDescription beanDesc, Boolean staticTyping, JsonSerializer keySerializer, TypeSerializer elementTypeSerializer, JsonSerializer elementValueSerializer)
   at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildContainerSerializer(SerializerProvider prov, JavaType type, BeanDescription beanDesc, Boolean staticTyping)
   at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(SerializerProvider prov, JavaType type, BeanDescription beanDesc, Boolean staticTyping)
   at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(SerializerProvider prov, JavaType origType)
   at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(JavaType type)
   at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(Class rawType)
   at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(Class valueType, BeanProperty property)
   at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(Class valueType, Boolean cache, BeanProperty property)
   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(JsonGenerator gen, Object value)
   at com.fasterxml.jackson.databind.ObjectMapper.writeValue(JsonGenerator g, Object value)
[...]

**Comment by TylerDurden23** [comment]
@igorkwwrd  Did you use the ikvmc build for .Net Core or for Framework?

**Comment by igorkwwrd** [comment]
@TylerDurden23 This relates to .NET core.  With framework build there is no issue.  Unfortunately I have no solution to the problem yet.

**Comment by TylerDurden23** [comment]
@igorkwwrd  I had issues with the ikvmc binary compiled for Core and used the one for framework. But i've noticed how you have addressed it (using the explicit references to the assemblies) - in the end it has not effect on the bug.

Still there - as long the code is run in a Core App using the Core assemblies.

**Comment by igorkwwrd** [comment]
Resolved by
https://github.com/ikvm-revived/ikvm/pull/25/commits/c4621f2e9718ac95c6f6697b0e94372686b1abb8

**Comment by NightOwl888** [comment]
Why was this issue reopened? Can it be closed?

**Comment by igorkwwrd** [comment]
@NightOwl888 No idea why it's reopened.  I believe it can be closed.

**Comment by NightOwl888** [comment]
Thanks. It would be great to clean up some of these open issues!
