### ISSUE TITLE
ikvmstubs netstandard not found

### ISSUE THREAD

**Issue by Frontrider** [ikvm-revived/ikvm#304]
I am on manjaro linux.

When trying to run ikvmstub, it returns this error:
```
Unhandled exception: System.IO.FileNotFoundException: netstandard
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in D:\a\ikvm\ikvm\src\IKVM.Reflection\Universe.cs:line 788
   at IKVM.Internal.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList`1 references, IList`1 userLibPaths) in D:\a\ikvm\ikvm\src\ikvmc\IKVM\Internal\AssemblyResolver.cs:line 93
   at IKVM.Tools.Exporter.IkvmExporterInternal.Execute(IkvmExporterOptions options) in D:\a\ikvm\ikvm\src\IKVM.Tools.Exporter\IkvmExporterInternal.cs:line 90
   at IKVM.Tools.Exporter.IkvmExporterTool.ExecuteAsync(InvocationContext context) in D:\a\ikvm\ikvm\src\IKVM.Tools.Exporter\IkvmExporterTool.cs:line 111
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

The ways I tried to run it:
- download from the releases tab
-  nuget install  IKVM.MSBuild.Tools.runtime.linux-x64, and then execute whatever it dumped into my project's folder
- add this to the csproj file:
```
<ItemGroup>
      <PackageReference Include="IKVM.MSBuild.Tools.runtime.linux-x64" Version="8.4.5" />
    </ItemGroup>
  <Target Name="PreBuild" AfterTargets="PostBuildEvent">
    <Exec Command="$(NuGetPackageRoot)ikvm.msbuild.tools.runtime.linux-x64/8.4.5/ikvmstub/netcoreapp3.1/linux-x64/ikvmstub ./api/GodotSharp.dll -o ./godot.jar" />
  </Target>
```

**Comment by wasabii** [comment]
ilvmstub requires every referenced assembly to be specified. Every single one.

Running it by hand is a fraught process without a tool to collect those references for your. Which is why IKVM.Net.SDK exists.

**Comment by Frontrider** [comment]
This is the only thing I could find from the available docs. How do I do it then?

**Comment by wasabii** [comment]
Specify every assembly that is required for your target by hand. -r parameter.

What are you trying to accomplish?

**Comment by Frontrider** [comment]
- Get a stub from godot's c# api (part where it fails)
- build kotlin/java code against that stub
- run it with godot's c# support

**Comment by Frontrider** [comment]
Okay, now it requests a different library. That is at least something I can play with.

**Comment by wasabii** [comment]
Well, I'm not totally sure how that can possibly work.... But I wish you luck.

**Comment by Frontrider** [comment]
Too much work for what it's worth.
