### ISSUE TITLE
Process to follow when package has other jar dependencies

### ISSUE THREAD

**Issue by askids** [ikvm-revived/ikvm#312]
hi,

I am trying to following the steps from wiki to generate DLL from JAR. But the sample used has no other dependencies. Now if the JAR that I have, has dependencies on other external JARs, do those additional JARs get included by default, when DLL is generated or do I need to generate DLL for each JAR individually? Also, is there  a sequence to follow? Can you please clarify?

Thanks!

**Comment by wasabii** [comment]
The Wiki isn't owned by us, as far as I know, nor been updated in like a decade. The instructions to properly make use of our preferred method is in the project README. And also shown in the description of the Nuget package.

**Comment by GeorgeS2019** [comment]
@askids 
Best u create a standalone Jar with all dependencies included..

**Comment by wasabii** [comment]
> @askids Best u create a standalone Jar with all dependencies included..

What George suggest is not best nor recommended.

Primarily we recommend MavenReference is your library is published in a Maven repository, and IkvmReference if it is not.

Manually execution of the various command line tools requires a good deal of knowledge, discovery of path information and dependencies.

**Comment by GeorgeS2019** [comment]
@wasabii I merely wrote something sufficiently so u will end up writing more to help @askids 

Beyond just sending him to read and good luck 😉

I win this round 😉

**Comment by wasabii** [comment]
You are attempting to deliberately mislead people in order to provoke me to give more detailed responses?

I kindly suggest you do not do that.

**Comment by GeorgeS2019** [comment]
@askids now he get an elaborated helpful answer 😉

**Comment by askids** [comment]
> The wiki isn't owned by us, as far as I know, nor been updated in like a decade. The instructions to properly make use of our preferred method is in the project README. And also shown in the description of the Nuget package.

Is there any sample project that shows how to use it end to end? From readme, I get that I should include IkvmReference for the required jars. Readme says that output assembly will be generated in the build process. However, its not clear on how do I use the the functionality from jar in my C# project. OR do I need to do this as a 2 step process. 1st have a dummy project with ikvmreference to generate the DLLs and then for actual usage, reference the generated DLL from the 1st step in another project. Is that how its supposed to be done?

**Comment by askids** [comment]
ok. I was able to make some progress. I created a dummy project. Added IkvmReference to my custom jar and it generated the DLL, when I only provide the AssemblyName, version and fileversion option in the ikvmReference. However, when I use this DLL within another project, it fails with Java classnotfound exception for a class from the dependent jar. If I add the References node on my dummy project with the external jar, then its not generating the DLL.

I see the below error logged in MSBuild logs file.
``
4/18/2023 3:27:19 PM
System.Runtime.Serialization.SerializationException: Type ‘IKVM.MSBuild.Tasks.IkvmTaskMessageException’ in Assembly ‘IKVM.MSBuild.Tasks, Version=8.4.5.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58’ is not marked as serializable.
at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header inHeaders, __BinaryWriter serWriter, Boolean fCheck)
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header headers, Boolean fCheck)
at Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.TranslateDotNet[T](T& value)
at Microsoft.Build.BackEnd.TaskHostTaskComplete.Translate(ITranslator translator)
at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
``

**Comment by askids** [comment]
Below is the error

``
java.lang.ClassNotFoundException: com.ibm.db2.jcc.DB2Driver
at IKVM.Java.Externs.java.lang.Class.forName0(Unknown Source)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:302)
at myjava.project.zload.ZLoadRunner.Load(ZLoadRunner.java:56)
at cli.MyDotnetProject.Core.DU.DataLoader.Services.DataLoader$$$003CRunProcess$$003Ed__20.MoveNext(DataLoader.cs:81)
at cli.System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(Unknown Source)
at cli.MyDotnetProject.Core.DU.DataLoader.Services.DataLoader.RunProcess(Unknown Source)
at cli.MyDotnetProject.Core.DU.DataLoader.Program.Main(Program.cs:35)
``

Below is the Java Code which is throwing error. I have db2jcc4.jar as external dependency for my java package.

``
Class.forName(“com.ibm.db2.jcc.DB2Driver”).newInstance();
``

**Comment by wasabii** [comment]
There is no need for a dummy project.

**Comment by askids** [comment]
> There is no need for a dummy project. You add the IkvmReference and then use the classes.
But that is the part that I dont get. How will it work without the dummy project. Without the DLL generated, how will I be able to refer to the Java classes and properties. My build will fail. I tried it anyway, by adding the IkvmReference directly to my main dotnet project with entries for both jar, but my compilation failed as expected as the classes from jar were not recognized.

**Comment by wasabii** [comment]
You add IkvmReference to your project, and you type in code that uses the classes. That is it. It functions like a regular PackageReference, ProjectReference, or Reference.

**Comment by wasabii** [comment]
Haven't heard anything, and I think this isn't an issue in Ikvm at this point. Closing. Reopen if there is a continuing issue.
