### ISSUE TITLE
System.IO.FileNotFoundException System.Runtime.Extensions Version=4.2.2.0 when converting .jar to dll

### ISSUE THREAD

**Issue by dmit25** [ikvm-revived/ikvm#33]
Hi, guys! Thank you for all the work you've done so far!

Branch `ikvm-build`

I'm trying to compile a dll out of jar with the .net core 3.1 version and getting this error

```
System.TypeInitializationException: The type initializer for 'IKVM.Internal.ClassLoaderWrapper' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'IKVM.Internal.PrimitiveTypeWrapper' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'IKVM.Internal.Types' threw an exception.
 ---> System.IO.FileNotFoundException: System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in C:\src\ikvm\reflect\Universe.cs:line 834
   at IKVM.Reflection.Universe.Load(String refname) in C:\src\ikvm\reflect\Universe.cs:line 793
   at IKVM.Reflection.Universe.Import(Assembly asm) in C:\src\ikvm\reflect\Universe.cs:line 666
   at IKVM.Reflection.Universe.ImportImpl(Type type) in C:\src\ikvm\reflect\Universe.cs:line 644
   at IKVM.Reflection.Universe.Import(Type type) in C:\src\ikvm\reflect\Universe.cs:line 579
   at IKVM.Internal.JVM.Import(Type type) in C:\src\ikvm\runtime\IKVM.Runtime\vm.cs:line 488
   at IKVM.Internal.Types..cctor() in C:\src\ikvm\runtime\IKVM.Runtime\Types.cs:line 61
   --- End of inner exception stack trace ---
   at IKVM.Internal.PrimitiveTypeWrapper..cctor() in C:\src\ikvm\runtime\IKVM.Runtime\TypeWrapper.cs:line 3731
   --- End of inner exception stack trace ---
   at IKVM.Internal.ClassLoaderWrapper..cctor() in C:\src\ikvm\runtime\IKVM.Runtime\ClassLoaderWrapper.cs:line 140
   --- End of inner exception stack trace ---
   at IKVM.Internal.ClassLoaderWrapper..ctor(CodeGenOptions codegenoptions, Object javaClassLoader) in C:\src\ikvm\runtime\IKVM.Runtime\ClassLoaderWrapper.cs:line 117
   at IKVM.Internal.CompilerClassLoader..ctor(AssemblyClassLoader[] referencedAssemblies, CompilerOptions options, FileInfo assemblyPath, Boolean targetIsModule, String assemblyName, Dictionary`2 classes, Boolean compilingCoreAssembly) in C:\src\ikvm\ikvmc\CompilerClassLoader.cs:line 79
   at IKVM.Internal.CompilerClassLoader.CreateCompiler(CompilerOptions options, CompilerClassLoader& loader, Boolean& compilingCoreAssembly) in C:\src\ikvm\ikvmc\CompilerClassLoader.cs:line 2846
   at IKVM.Internal.CompilerClassLoader.Compile(String runtimeAssembly, List`1 optionsList) in C:\src\ikvm\ikvmc\CompilerClassLoader.cs:line 2576
   at IkvmcCompiler.Compile(String[] args) in C:\src\ikvm\ikvmc\Compiler.cs:line 320
   at IkvmcCompiler.Main(String[] args) in C:\src\ikvm\ikvmc\Compiler.cs:line 242
```

ikvm was built without any errors (only deprecation warnings), jar file was built with openjdk-8u45-b14. Any ideas what could cause this problem?

**Comment by ams-tschoening** [comment]
The following is the problem:

> System.IO.FileNotFoundException: System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

I suggest to provide more details about how exactly you built IKVMC and how exactly you tried to create the DLL. Project files, command lines etc. might be of help. When you search for the above line, you get many hints of mismatches between core and standard and framework and ...

https://developercommunity.visualstudio.com/t/filenotfoundexception-systemruntime-version4220-wh/1114518
https://stackoverflow.com/questions/59610009/net-core-3-1-could-not-load-file-or-assembly-system-runtime-version-4-2-2-0
https://github.com/Azure/azure-functions-vs-build-sdk/issues/160

**Comment by igorkwwrd** [comment]
You have to provide a reference to the ikvmc compiler. Since the .NET Core is highly modular (as opposed to the .NET Framework where the most staff resides in mscorlib.dll), there are many references that you need to provide explicitly.

In this case
ikvmc -r:System.Runtime.Extensions ...

Then you likely to get a few more not found exceptions. And again, provide the missing references using the -r switch.

**Comment by dmit25** [comment]
Thank you, @igorkwwrd 👍 ! Yeah, as everything was built without dependencies, you have to explicitly add missing dlls as references.
