### ISSUE TITLE
log4j fails with The invoked member is not supported in a dynamic assembly

### ISSUE THREAD

**Issue by AliveDevil** [ikvm-revived/ikvm#45]
There is still so much more to do to support .NET Core, than just getting it build on .NET Core.
The whole dynamic-assembly modules need to be reworked in order to interop correctly with core.

I.e. Log4j crashes completely while setting up the LoggerContext:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'ch.cyberduck.core.preferences.DefaultPreferences' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'ch.cyberduck.core.preferences.Preferences' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'org.apache.logging.log4j.core.config.ConfigurationFactory' threw an exception.
 ---> System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at Java_java_lang_Class.forName0(String name, Boolean initialize, ClassLoader loader, Class caller) in ikvm-revived\runtime\IKVM.Runtime\openjdk\java.lang.cs:line 76
   at java.lang.Class.forName0(String name, Boolean initialize, ClassLoader loader, Class caller)
   at java.lang.Class.forName(String className, CallerID )
   at org.apache.logging.log4j.util.LoaderUtil.loadClass(String className)
   at org.apache.logging.log4j.util.LoaderUtil.newInstanceOf(String className)
   at org.apache.logging.log4j.util.LoaderUtil.newCheckedInstanceOf(String className, Class clazz)
   at org.apache.logging.log4j.core.util.Loader.newCheckedInstanceOf(String className, Class clazz)
   at org.apache.logging.log4j.core.lookup.Interpolator..ctor(Map properties)
   at org.apache.logging.log4j.core.lookup.Interpolator..ctor()
   at org.apache.logging.log4j.core.config.ConfigurationFactory..ctor()
   at org.apache.logging.log4j.core.config.ConfigurationFactory.Factory..ctor()
   at org.apache.logging.log4j.core.config.ConfigurationFactory.Factory..ctor(1 x0)
   at org.apache.logging.log4j.core.config.ConfigurationFactory..cctor()
   --- End of inner exception stack trace ---
   at org.apache.logging.log4j.core.config.ConfigurationFactory.getInstance()
   at org.apache.logging.log4j.core.LoggerContext.reconfigure(URI configURI)
   at org.apache.logging.log4j.core.LoggerContext.reconfigure()
   at org.apache.logging.log4j.core.LoggerContext.start()
   at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(String fqcn, ClassLoader loader, Object externalContext, Boolean currentContext)
   at org.apache.logging.log4j.core.impl.Log4jContextFactory.<bridge>getContext(String fqcn, ClassLoader loader, Object externalContext, Boolean currentContext)
   at org.apache.logging.log4j.core.impl.Log4jContextFactory.__<overridestub>org.apache.logging.log4j.spi.LoggerContextFactory::getContext(String , ClassLoader , Object , Boolean )
   at org.apache.logging.log4j.LogManager.getContext(ClassLoader loader, Boolean currentContext)
   at org.apache.logging.log4j.LogManager.getLogger(Class clazz)
   at ch.cyberduck.core.preferences.Preferences..cctor()
   --- End of inner exception stack trace ---
   at ch.cyberduck.core.preferences.Preferences.__<clinit>()
   at ch.cyberduck.core.preferences.DefaultPreferences..cctor()
   --- End of inner exception stack trace ---
   at ch.cyberduck.core.preferences.DefaultPreferences..ctor()
   at Ch.Cyberduck.Core.Preferences.AppConfigPreferences..ctor(Locales locales)
   at Ch.Cyberduck.Cli.WindowsTerminalPreferences..ctor() in cyberduck\cli\src\main\csharp\ch\cyberduck\cli\WindowsTerminalPreferences.cs:line 36
   at Ch.Cyberduck.Cli.WindowsTerminal.Main(String[] args) in cyberduck\cli\src\main\csharp\ch\cyberduck\cli\WindowsTerminal.cs:line 38
```

Offending java source: https://github.com/apache/logging-log4j2/blob/rel/2.17.1/log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/Interpolator.java#L117

**Comment by NightOwl888** [comment]
Hi there. Could you please try again with https://www.nuget.org/packages/IKVM/8.2.0-prerelease0379 and report back whether this is still an issue?

**Comment by AliveDevil** [comment]
Currently blocked by #65.
