### ISSUE TITLE
IKVM.Reflection.MissingMemberException (System.Diagnostics.DebuggableAttribute) when using IKVMC

### ISSUE THREAD

**Issue by vokounjan** [ikvm-revived/ikvm#66]
Hi,

sorry for spamming with issues but I believe that this has a different cause than #65 and it seems like I'm the first encoutering it.

After switching from previous IKVMC to current pre-release and running this command:

`PS C:\Users\vokounjan\source\repos\Company.Product> dotnet exec C:\Users\vokounjan\source\repos\Company.Product\bin\IKVM\ikvmc.dll -target:library -out:C:\Users\vokounjan\source\repos\Company.Product\bin\MyLibrary\MyLibrary.dll -version:1.2.3 -r:System.Runtime.Extensions.dll -r:System.Runtime.dll -r:System.Threading.dll -r:System.Threading.Thread.dll C:\Users\vokounjan\source\repos\Company.Product\jar\MyLibrary\MyLibrary.jar`

Now I get this problem:

```
IKVM.NET Compiler (8.2.0-prerelease.392)
Copyright © 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug


*** INTERNAL COMPILER ERROR ***

PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE

ikvmc, Version=8.2.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
C:\Users\vokounjan\source\repos\Company.Product\bin\IKVM\
3.1.25 64-bit

IKVM.Reflection.MissingMemberException: Member 'System.Diagnostics.DebuggableAttribute' is a missing member and does not support the requested operation.
   at IKVM.Reflection.MissingType.__GetDeclaredMethods() in D:\a\ikvm\ikvm\IKVM.Reflection\Missing.cs:line 523
   at IKVM.Reflection.Type.GetMembers[T]() in D:\a\ikvm\ikvm\IKVM.Reflection\Type.cs:line 749
   at IKVM.Reflection.Type.GetMemberByName[T](String name, BindingFlags flags, Predicate`1 filter) in D:\a\ikvm\ikvm\IKVM.Reflection\Type.cs:line 811
   at IKVM.Reflection.Type.GetConstructorImpl(String name, BindingFlags bindingAttr, Binder binder, Type[] types, ParameterModifier[] modifiers) in D:\a\ikvm\ikvm\IKVM.Reflection\Type.cs:line 1074
   at IKVM.Reflection.Type.GetConstructor(BindingFlags bindingAttr, Binder binder, Type[] types, ParameterModifier[] modifiers) in D:\a\ikvm\ikvm\IKVM.Reflection\Type.cs:line 1054
   at IKVM.Reflection.Type.GetConstructor(BindingFlags bindingAttr, Binder binder, CallingConventions callingConvention, Type[] types, ParameterModifier[] modifiers) in D:\a\ikvm\ikvm\IKVM.Reflection\Type.cs:line 1082
   at IKVM.Reflection.Type.GetConstructor(Type[] types) in D:\a\ikvm\ikvm\IKVM.Reflection\Type.cs:line 1046
   at IKVM.Internal.CompilerClassLoader.CreateModuleBuilder() in D:\a\ikvm\ikvm\ikvmc\IKVM\Internal\CompilerClassLoader.cs:line 155
   at IKVM.Internal.DynamicClassLoader.Get(ClassLoaderWrapper loader) in D:\a\ikvm\ikvm\IKVM.Runtime\DynamicClassLoader.cs:line 466
   at IKVM.Internal.ClassLoaderWrapper.GetTypeWrapperFactory() in D:\a\ikvm\ikvm\IKVM.Runtime\ClassLoaderWrapper.cs:line 500
   at IKVM.Internal.ClassLoaderWrapper.DefineClassCritical(ClassFile f, Object protectionDomain) in D:\a\ikvm\ikvm\IKVM.Runtime\ClassLoaderWrapper.cs:line 458
   at IKVM.Internal.ClassLoaderWrapper.DefineClass(ClassFile f, Object protectionDomain) in D:\a\ikvm\ikvm\IKVM.Runtime\ClassLoaderWrapper.cs:line 439
   at IKVM.Internal.CompilerClassLoader.GetTypeWrapperCompilerHook(String name) in D:\a\ikvm\ikvm\ikvmc\IKVM\Internal\CompilerClassLoader.cs:line 359
   at IKVM.Internal.CompilerClassLoader.LoadClassImpl(String name, LoadMode mode) in D:\a\ikvm\ikvm\ikvmc\IKVM\Internal\CompilerClassLoader.cs:line 227
   at IKVM.Internal.ClassLoaderWrapper.LoadClass(String name, LoadMode mode) in D:\a\ikvm\ikvm\IKVM.Runtime\ClassLoaderWrapper.cs:line 536
   at IKVM.Internal.CompilerClassLoader.CompilePass1() in D:\a\ikvm\ikvm\ikvmc\IKVM\Internal\CompilerClassLoader.cs:line 2994
   at IKVM.Internal.CompilerClassLoader.Compile(String runtimeAssembly, List`1 optionsList) in D:\a\ikvm\ikvm\ikvmc\IKVM\Internal\CompilerClassLoader.cs:line 2627
   at ikvmc.IkvmcCompiler.Compile(String[] args) in D:\a\ikvm\ikvm\ikvmc\IkvmcCompiler.cs:line 190
   at ikvmc.IkvmcCompiler.Main(String[] args) in D:\a\ikvm\ikvm\ikvmc\IkvmcCompiler.cs:line 112
```

Any idea?

Thanks

**Comment by wasabii** [comment]
@vokounjan  I did answer this on the other thread, but I figured I would repeat it here, since it applies more directly to this.

Pass these options to ikvmc: -nostdlib -lib:PathToRuntimeFolderWhereverThatIs

**Comment by vokounjan** [comment]
@wasabii 

I must have missed that, thank you!
